language: java

jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

install:
  - ./gradlew assemble -x signArchives

script:
  - ./gradlew check -x signArchives

after_success:
  - bash <(curl -s https://codecov.io/bash)
